Dựa trên thể thức của MSI 2026, khả năng cao sẽ có 2 đội LCK và 2 đội LPL trong Bracket Stage -> meta LCK/LPL sẽ có ảnh hưởng lớn hơn. Vì vậy, người viết sẽ sử dụng dữ liệu của các giải đấu sau: 
- LCK 2026 Split 1-2
- LCK 2026 Road to MSI
- LPL 2026 Split 2
- LPL 2026 Split 2 Playoffs

Dữ liệu được tải về từ Oracle's Elixir.

# Tướng

In [1]:
import pandas as pd
import numpy as np

lck_playoffs_champ = pd.read_csv("MSI 2026 data\\LCK 2026 Road to MSI - Champion Stats - OraclesElixir.csv")
lck_champ = pd.read_csv("MSI 2026 data\\LCK 2026 Rounds 1-2 - Champion Stats - OraclesElixir.csv")
lpl_playoffs_champ = pd.read_csv("MSI 2026 data\\LPL 2026 Split 2 Playoffs - Champion Stats - OraclesElixir.csv")
lpl_champ = pd.read_csv("MSI 2026 data\\LPL 2026 Split 2 - Champion Stats - OraclesElixir.csv")

In [2]:
# Tiền xử lý dữ liệu để tính toán các chỉ số cần thiết
lck_playoffs_number_of_games = 20
lck_number_of_games = 204
lpl_playoffs_number_of_games = 68
lpl_number_of_games = 171

def convert_percentage_to_float(value):
    if isinstance(value, object) and str(value).endswith('%'):
        return float(str(value).strip('%')) / 100
    return value

lck_playoffs_champ['B%'] = lck_playoffs_champ['B%'].apply(convert_percentage_to_float)
lck_champ['B%'] = lck_champ['B%'].apply(convert_percentage_to_float)
lpl_playoffs_champ['B%'] = lpl_playoffs_champ['B%'].apply(convert_percentage_to_float)
lpl_champ['B%'] = lpl_champ['B%'].apply(convert_percentage_to_float)

lck_playoffs_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lck_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lpl_playoffs_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)
lpl_champ.rename(columns={'B%': 'Ban Rate'}, inplace=True)

lck_playoffs_champ['Games Banned'] = lck_playoffs_champ['Ban Rate'] * lck_playoffs_number_of_games
lck_playoffs_champ['Games Banned'] = lck_playoffs_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lck_champ['Games Banned'] = lck_champ['Ban Rate'] * lck_number_of_games
lck_champ['Games Banned'] = lck_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lpl_playoffs_champ['Games Banned'] = lpl_playoffs_champ['Ban Rate'] * lpl_playoffs_number_of_games
lpl_playoffs_champ['Games Banned'] = lpl_playoffs_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)
lpl_champ['Games Banned'] = lpl_champ['Ban Rate'] * lpl_number_of_games
lpl_champ['Games Banned'] = lpl_champ['Games Banned'].apply(lambda x: round(x) if x != '' else 0)

In [3]:
champ = pd.concat([lck_playoffs_champ, lck_champ, lpl_playoffs_champ, lpl_champ], ignore_index=True)
champ

,Champion,Pos,GP,P%,Ban Rate,P+B%,W%,CTR%,K,D,...,XPD10,CSD10,CSPM,CS%P15,DPM,DMG%,GOLD%,WPM,WCPM,Games Banned
0,Naafiri,Jungle,5,25.0%,0.150,40.0%,60%,80%,24,17,...,-103,-1.8,7,18.4%,609,22.0%,21.4%,0.37,0.45,3
1,Rakan,Support,5,25.0%,0.100,35.0%,40%,60%,0,12,...,-70,-1.2,1.2,2.9%,113,4.4%,10.3%,2.48,0.78,2
2,Rumble,Top,5,25.0%,0.100,35.0%,20%,0%,11,14,...,195,0.4,7.9,20.6%,568,24.6%,19.1%,0.57,0.11,2
3,Ryze,Middle,5,25.0%,0.150,40.0%,80%,0%,21,11,...,235,6.2,9.5,26.0%,657,20.1%,21.9%,0.41,0.23,3
4,Xayah,ADC,5,25.0%,0.100,35.0%,20%,20%,20,14,...,77,6.2,11.4,33.4%,593,23.9%,28.4%,0.43,0.41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Zaahen,Jungle,1,0.6%,0.000,1.8%,0%,100%,1,2,...,-,-,6.7,-,103,6.2%,18.4%,0.36,0.57,0
458,Kennen,-,0,0%,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
459,Kha'Zix,-,0,0%,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
460,Leona,-,0,0%,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1
461,Ornn,-,0,0%,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,-,1

### Làm sạch và tiền xử lý dữ liệu

In [4]:
champ[['W%', 'P%']] = champ[['W%', 'P%']].applymap(convert_percentage_to_float)
champ.rename(columns={'W%': 'Win Rate', 'P%': 'Pick Rate'}, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26704\955472751.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  champ[['W%', 'P%']] = champ[['W%', 'P%']].applymap(convert_percentage_to_float)

In [5]:
champ['Game Win'] = champ['GP'] * champ['Win Rate']
champ['Game Win'] = champ['Game Win'].apply(lambda x: round(x) if x != '' else 0)
champ

,Champion,Pos,GP,Pick Rate,Ban Rate,P+B%,Win Rate,CTR%,K,D,...,CSD10,CSPM,CS%P15,DPM,DMG%,GOLD%,WPM,WCPM,Games Banned,Game Win
0,Naafiri,Jungle,5,0.250,0.150,40.0%,0.6,80%,24,17,...,-1.8,7,18.4%,609,22.0%,21.4%,0.37,0.45,3,3
1,Rakan,Support,5,0.250,0.100,35.0%,0.4,60%,0,12,...,-1.2,1.2,2.9%,113,4.4%,10.3%,2.48,0.78,2,2
2,Rumble,Top,5,0.250,0.100,35.0%,0.2,0%,11,14,...,0.4,7.9,20.6%,568,24.6%,19.1%,0.57,0.11,2,1
3,Ryze,Middle,5,0.250,0.150,40.0%,0.8,0%,21,11,...,6.2,9.5,26.0%,657,20.1%,21.9%,0.41,0.23,3,4
4,Xayah,ADC,5,0.250,0.100,35.0%,0.2,20%,20,14,...,6.2,11.4,33.4%,593,23.9%,28.4%,0.43,0.41,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Zaahen,Jungle,1,0.006,0.000,1.8%,0.0,100%,1,2,...,-,6.7,-,103,6.2%,18.4%,0.36,0.57,0,0
458,Kennen,-,0,0.000,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,1,0
459,Kha'Zix,-,0,0.000,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,1,0
460,Leona,-,0,0.000,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,1,0
461,Ornn,-,0,0.000,0.006,0.6%,-,-,-,-,...,-,-,-,-,-,-,-,-,1,0

In [6]:
champ['K'] = champ['K'].apply(lambda x: int(x) if x != '-' else 0)

### Vị tướng nào sẽ được chọn nhiều nhất?

In [7]:
champ[['Champion','GP']].groupby('Champion')['GP'].sum().sort_values(ascending=False).head(15)

Champion
Xin Zhao     143
Ryze         135
Jarvan IV    133
Ezreal       132
Jayce        118
Pantheon     118
Bard         113
Gnar         113
Annie        113
Seraphine    111
Lulu         109
Sion         105
Ashe         103
Yunara       103
Vi            99
Name: GP, dtype: int64

### Vị tướng nào sẽ có tỉ lệ thắng cao nhất? (được sử dụng trong tối thiểu 5 trận)

In [8]:
champ_above_5_games = champ.groupby('Champion')['GP'].sum().sort_values()
champ_above_5_games_list = champ_above_5_games[champ_above_5_games >= 5].index.tolist()

In [9]:
total_games_per_champ = champ[champ['Champion'].isin(champ_above_5_games_list)].where(champ['GP'] > 0).groupby('Champion').agg({'GP': 'sum', 'Game Win': 'sum'})
total_games_per_champ['Win Rate'] = total_games_per_champ['Game Win'] / total_games_per_champ['GP']
total_games_per_champ.sort_values(by='Win Rate', ascending=False)

             GP  Game Win  Win Rate
Champion
Lissandra   8.0       7.0  0.875000
Ornn        6.0       5.0  0.833333
Lux        16.0      12.0  0.750000
Kog'Maw     7.0       5.0  0.714286
Camille    10.0       7.0  0.700000
...         ...       ...       ...
Taliyah    31.0      10.0  0.322581
Rell       13.0       4.0  0.307692
Kai'Sa     10.0       3.0  0.300000
Gwen       10.0       3.0  0.300000
Aatrox      6.0       1.0  0.166667

[89 rows x 3 columns]

Người viết bỏ qua các tướng như Lissandra, Ornn... do số lượng trận đấu quá ít -> chọn Vayne cho mục này.

### Vị tướng nào sẽ có tỉ lệ thua cao nhất? (được sử dụng trong tối thiểu 5 trận))

In [10]:
total_games_per_champ.sort_values(by='Win Rate', ascending=True)

             GP  Game Win  Win Rate
Champion
Aatrox      6.0       1.0  0.166667
Kai'Sa     10.0       3.0  0.300000
Gwen       10.0       3.0  0.300000
Rell       13.0       4.0  0.307692
Taliyah    31.0      10.0  0.322581
...         ...       ...       ...
Camille    10.0       7.0  0.700000
Kog'Maw     7.0       5.0  0.714286
Lux        16.0      12.0  0.750000
Ornn        6.0       5.0  0.833333
Lissandra   8.0       7.0  0.875000

[89 rows x 3 columns]

### Vị tướng nào sẽ đạt được nhiều mạng hạ gục nhất?

In [11]:
champ[['Champion','K']].groupby('Champion')['K'].sum().sort_values(ascending=False).head(15)

Champion
Ezreal       533
Pantheon     485
Ryze         454
Ashe         449
Yunara       432
Jhin         409
Xin Zhao     401
Aurora       369
Jarvan IV    357
Lucian       342
Jayce        338
Lee Sin      332
Naafiri      330
Annie        324
Corki        319
Name: K, dtype: int64

### Vị tướng nào sẽ bị cấm nhiều nhất?

In [12]:
champ[['Champion','Games Banned']].groupby('Champion')['Games Banned'].sum().sort_values(ascending=False).head(15)

Champion
Varus           722
Rumble          437
Orianna         343
Karma           258
Nocturne        224
Ambessa         168
Bard            162
Jarvan IV       158
Jayce           143
Nautilus        129
Twisted Fate    128
Ashe            120
Akali           118
Vi              115
Annie           111
Name: Games Banned, dtype: int64

# Tuyển thủ

In [13]:
lck_playoffs_player = pd.read_csv("MSI 2026 data\\LCK 2026 Road to MSI - Player Stats - OraclesElixir.csv")
lck_player = pd.read_csv("MSI 2026 data\\LCK 2026 Rounds 1-2 - Player Stats - OraclesElixir.csv")
lpl_playoffs_player = pd.read_csv("MSI 2026 data\\LPL 2026 Split 2 Playoffs - Player Stats - OraclesElixir.csv")
lpl_player = pd.read_csv("MSI 2026 data\\LPL 2026 Split 2 - Player Stats - OraclesElixir.csv")

msi_team = ['T1', 'Hanwha Life Esports', 'Top Esports', 'Bilibili Gaming']

player = pd.concat([lck_playoffs_player, lpl_playoffs_player, lck_player, lpl_player], ignore_index=True)

In [14]:
player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DPM,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM
0,Smash,Dplus Kia,ADC,8,63%,63%,45,12,37,6.8,...,815,30.4%,31.5%,10418.0,414,29.7%,0.0,0.51,0.21,0.32
1,Zeka,Hanwha Life Esports,Middle,4,75%,0%,18,8,29,5.9,...,760,25.9%,25.3%,9633.0,304,22.1%,0.0,0.46,0.23,0.16
2,Delight,Hanwha Life Esports,Support,4,75%,100%,8,8,36,5.5,...,235,7.2%,6.7%,1073.0,159,11.4%,0.0,2.11,0.69,0.62
3,Career,Dplus Kia,Support,8,63%,38%,8,17,80,5.2,...,200,7.5%,5.5%,1718.0,146,10.7%,0.0,2.07,0.78,0.63
4,Chovy,Gen.G,Middle,8,63%,50%,33,19,60,4.9,...,852,27.7%,27.1%,7554.0,293,22.2%,0.0,0.39,0.09,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,Ycx,LGD Gaming,Support,12,50%,58%,8,30,97,3.5,...,141,6.1%,NaN,NaN,126,10.1%,NaN,1.97,0.55,0.41
229,Zdz,EDward Gaming,Top,14,50%,57%,30,38,68,2.6,...,592,24.6%,NaN,NaN,268,21.5%,NaN,0.51,0.21,0.21
230,Zhuo,Ninjas in Pyjamas,Support,33,48%,64%,23,83,350,4.5,...,214,8.0%,NaN,NaN,136,10.6%,NaN,1.90,0.43,0.49
231,Zika,Weibo Gaming,Top,35,46%,46%,81,100,166,2.5,...,599,22.8%,NaN,NaN,240,19.4%,NaN,0.38,0.14,0.19
232,ZUIAN,Top Esports,Top,30,60%,60%,75,93,164,2.6,...,592,20.9%,NaN,NaN,256,19.7%,NaN,0.47,0.15,0.17

In [15]:
msi_player = player.where(player['Team'].isin(msi_team))
msi_player.dropna(inplace = True, how = 'all')
msi_player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DPM,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM
1,Zeka,Hanwha Life Esports,Middle,4.0,75%,0%,18.0,8.0,29.0,5.9,...,760.0,25.9%,25.3%,9633.0,304.0,22.1%,0.0,0.46,0.23,0.16
2,Delight,Hanwha Life Esports,Support,4.0,75%,100%,8.0,8.0,36.0,5.5,...,235.0,7.2%,6.7%,1073.0,159.0,11.4%,0.0,2.11,0.69,0.62
8,Gumayusi,Hanwha Life Esports,ADC,4.0,75%,25%,20.0,9.0,21.0,4.6,...,887.0,27.3%,30.1%,8874.0,357.0,25.9%,0.0,0.53,0.24,0.35
9,Peyz,T1,ADC,9.0,44%,67%,39.0,22.0,60.0,4.5,...,866.0,31.6%,34.2%,6966.0,379.0,29.3%,0.0,0.39,0.09,0.39
10,Kanavi,Hanwha Life Esports,Jungle,4.0,75%,50%,13.0,12.0,38.0,4.3,...,564.0,18.3%,17.8%,6910.0,284.0,20.6%,2.0,0.37,0.28,0.42
17,Oner,T1,Jungle,9.0,44%,44%,36.0,30.0,61.0,3.2,...,512.0,18.6%,19.9%,1609.0,271.0,21.1%,1.0,0.32,0.25,0.43
18,Keria,T1,Support,9.0,44%,33%,5.0,36.0,94.0,2.8,...,194.0,7.0%,5.8%,1226.0,126.0,9.8%,0.0,2.43,1.02,0.39
19,Zeus,Hanwha Life Esports,Top,4.0,75%,75%,11.0,13.0,26.0,2.8,...,692.0,21.2%,20.1%,9336.0,274.0,20.0%,0.0,0.47,0.21,0.15
20,Doran,T1,Top,9.0,44%,44%,20.0,31.0,60.0,2.6,...,602.0,22.2%,20.3%,5601.0,256.0,19.9%,0.0,0.39,0.14,0.19
22,Faker,T1,Middle,9.0,44%,67%,27.0,36.0,60.0,2.4,...,566.0,20.6%,19.9%,7509.0,257.0,20.0%,0.0,0.41,0.14,0.24
35,Bin,Bilibili Gaming,Top,22.0,73%,41%,77.0,49.0,157.0,4.8,...,657.0,21.6%,NaN,NaN,280.0,20.6%,NaN,0.39,0.10,0.16
40,Creme,Top Esports,Middle,13.0,69%,54%,47.0,29.0,97.0,5.0,...,745.0,26.9%,NaN,NaN,278.0,20.9%,NaN,0.50,0.12,0.27
46,fengyue,Top Esports,Support,13.0,69%,38%,8.0,31.0,151.0,5.1,...,190.0,6.9%,NaN,NaN,139.0,10.5%,NaN,2.09,0.59,0.40
55,JackeyLove,Top Esports,ADC,13.0,69%,62%,63.0,32.0,71.0,4.2,...,776.0,27.6%,NaN,NaN,359.0,27.2%,NaN,0.39,0.16,0.37
64,Knight,Bilibili Gaming,Middle,22.0,73%,55%,148.0,36.0,155.0,8.4,...,865.0,27.8%,NaN,NaN,323.0,23.6%,NaN,0.34,0.13,0.22
70,ON,Bilibili Gaming,Support,22.0,73%,50%,16.0,90.0,299.0,3.5,...,277.0,8.9%,NaN,NaN,147.0,10.7%,NaN,2.19,0.69,0.58
79,Tian,Top Esports,Jungle,13.0,69%,69%,49.0,38.0,90.0,3.7,...,446.0,16.0%,NaN,NaN,280.0,21.2%,NaN,0.38,0.29,0.41
81,Viper,Bilibili Gaming,ADC,22.0,73%,64%,104.0,55.0,188.0,5.3,...,811.0,26.5%,NaN,NaN,355.0,25.9%,NaN,0.60,0.24,0.38
86,Xun,Bilibili Gaming,Jungle,22.0,73%,50%,73.0,61.0,239.0,5.1,...,482.0,15.2%,NaN,NaN,262.0,19.2%,NaN,0.39,0.26,0.30
91,ZUIAN,Top Esports,Top,13.0,69%,31%,39.0,33.0,82.0,3.7,...,640.0,22.6%,NaN,NaN,267.0,20.1%,NaN,0.44,0.13,0.15
95,Bluffing,Hanwha Life Esports,Support,3.0,67%,33%,4.0,12.0,41.0,3.8,...,303.0,9.7%,9.2%,1141.0,160.0,11.5%,0.0,1.92,0.36,0.42
105,Delight,Hanwha Life Esports,Support,40.0,75%,50%,47.0,109.0,491.0,4.9,...,223.0,7.4%,5.4%,1115.0,157.0,11.2%,0.0,1.91,0.37,0.55
109,Doran,T1,Top,40.0,75%,38%,123.0,130.0,234.0,2.7,...,673.0,22.9%,22.0%,7102.0,264.0,19.6%,0.0,0.42,0.16,0.18
114,Faker,T1,Middle,40.0,75%,53%,156.0,120.0,247.0,3.4,...,686.0,23.1%,22.6%,8816.0,289.0,21.3%,0.0,0.46,0.14,0.25
117,Gumayusi,Hanwha Life Esports,ADC,43.0,74%,58%,196.0,122.0,337.0,4.4,...,806.0,26.8%,28.0%,10837.0,379.0,26.9%,0.0,0.52,0.20,0.36
119,Kanavi,Hanwha Life Esports,Jungle,43.0,74%,42%,166.0,157.0,381.0,3.5,...,553.0,18.5%,19.7%,3298.0,287.0,20.4%,4.0,0.35,0.30,0.42
121,Keria,T1,Support,40.0,75%,50%,47.0,104.0,467.0,4.9,...,289.0,9.7%,7.6%,1464.0,148.0,10.8%,0.0,2.18,0.49,0.40
130,Oner,T1,Jungle,40.0,75%,58%,152.0,117.0,331.0,4.1,...,491.0,16.4%,17.5%,2559.0,275.0,20.3%,5.0,0.37,0.27,0.43
133,Peyz,T1,ADC,40.0,75%,55%,212.0,91.0,256.0,5.1,...,823.0,28.0%,30.2%,8720.0,382.0,28.0%,1.0,0.42,0.13,0.36
154,Zeka,Hanwha Life Esports,Middle,43.0,74%,53%,226.0,86.0,299.0,6.1,...,743.0,24.9%,26.1%,7577.0,308.0,21.8%,0.0,0.41,0.18,0.23
155,Zeus,Hanwha Life Esports,Top,43.0,74%,49%,142.0,112.0,285.0,3.8,...,664.0,22.2%,20.7%,9623.0,275.0,19.6%,0.0,0.46,0.16,0.15
161,Bin,Bilibili Gaming,Top,32.0,75%,28%,87.0,87.0,202.0,3.3,...,609.0,19.8%,NaN,NaN,274.0,19.6%,NaN,0.45,0.12,0.19
167,Creme,Top Esports,Middle,30.0,60%,53%,102.0,70.0,192.0,4.2,...,753.0,26.4%,NaN,NaN,284.0,21.6%,NaN,0.41,0.11,0.24
173,fengyue,Top Esports,Support,30.0,60%,43%,25.0,102.0,332.0,3.5,...,221.0,8.0%,NaN,NaN,143.0,11.0%,NaN,1.96,0.55,0.41
186,JackeyLove,Top Esports,ADC,30.0,60%,63%,146.0,84.0,168.0,3.7,...,797.0,28.2%,NaN,NaN,351.0,26.6%,NaN,0.37,0.14,0.42
196,Knight,Bilibili Gaming,Middle,32.0,75%,50%,224.0,52.0,228.0,8.7,...,800.0,25.7%,NaN,NaN,328.0,23.5%,NaN,0.33,0.12,0.28
203,ON,Bilibili Gaming,Support,32.0,75%,53%,19.0,98.0,432.0,4.6,...,228.0,7.5%,NaN,NaN,148.0,10.6%,NaN,2.19,0.69,0.48
218,Tian,Top Esports,Jungle,30.0,60%,37%,108.0,92.0,230.0,3.7,...,470.0,16.5%,NaN,NaN,277.0,21.1%,NaN,0.42,0.34,0.40
221,Viper,Bilibili Gaming,ADC,32.0,75%,41%,165.0,79.0,254.0,5.3,...,919.0,30.3%,NaN,NaN,369.0,26.2%,NaN,0.62,0.26,0.34
227,Xun,Bilibili Gaming,Jungle,32.0,75%,59%,142.0,94.0,308.0,4.8,...,515.0,16.7%,NaN,NaN,280.0,20.1%,NaN,0.32,0.26,0.31
232,ZUIAN,Top Esports,Top,30.0,60%,60%,75.0,93.0,164.0,2.6,...,592.0,20.9%,NaN,NaN,256.0,19.7%,NaN,0.47,0.15,0.17

### Làm sạch và tiền xử lý dữ liệu

In [16]:
msi_player['FB%'] = msi_player['FB%'].apply(convert_percentage_to_float)
msi_player.rename(columns={'FB%': 'First Blood Rate'}, inplace=True)

In [17]:
msi_player['First Blood'] = msi_player['First Blood Rate'] * msi_player['GP']
msi_player['First Blood'] = msi_player['First Blood'].apply(lambda x: round(x) if not pd.isnull(x) else 0)
msi_player

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM,First Blood
1,Zeka,Hanwha Life Esports,Middle,4.0,75%,0%,18.0,8.0,29.0,5.9,...,25.9%,25.3%,9633.0,304.0,22.1%,0.0,0.46,0.23,0.16,0
2,Delight,Hanwha Life Esports,Support,4.0,75%,100%,8.0,8.0,36.0,5.5,...,7.2%,6.7%,1073.0,159.0,11.4%,0.0,2.11,0.69,0.62,1
8,Gumayusi,Hanwha Life Esports,ADC,4.0,75%,25%,20.0,9.0,21.0,4.6,...,27.3%,30.1%,8874.0,357.0,25.9%,0.0,0.53,0.24,0.35,1
9,Peyz,T1,ADC,9.0,44%,67%,39.0,22.0,60.0,4.5,...,31.6%,34.2%,6966.0,379.0,29.3%,0.0,0.39,0.09,0.39,3
10,Kanavi,Hanwha Life Esports,Jungle,4.0,75%,50%,13.0,12.0,38.0,4.3,...,18.3%,17.8%,6910.0,284.0,20.6%,2.0,0.37,0.28,0.42,3
17,Oner,T1,Jungle,9.0,44%,44%,36.0,30.0,61.0,3.2,...,18.6%,19.9%,1609.0,271.0,21.1%,1.0,0.32,0.25,0.43,3
18,Keria,T1,Support,9.0,44%,33%,5.0,36.0,94.0,2.8,...,7.0%,5.8%,1226.0,126.0,9.8%,0.0,2.43,1.02,0.39,3
19,Zeus,Hanwha Life Esports,Top,4.0,75%,75%,11.0,13.0,26.0,2.8,...,21.2%,20.1%,9336.0,274.0,20.0%,0.0,0.47,0.21,0.15,2
20,Doran,T1,Top,9.0,44%,44%,20.0,31.0,60.0,2.6,...,22.2%,20.3%,5601.0,256.0,19.9%,0.0,0.39,0.14,0.19,0
22,Faker,T1,Middle,9.0,44%,67%,27.0,36.0,60.0,2.4,...,20.6%,19.9%,7509.0,257.0,20.0%,0.0,0.41,0.14,0.24,1
35,Bin,Bilibili Gaming,Top,22.0,73%,41%,77.0,49.0,157.0,4.8,...,21.6%,NaN,NaN,280.0,20.6%,NaN,0.39,0.10,0.16,0
40,Creme,Top Esports,Middle,13.0,69%,54%,47.0,29.0,97.0,5.0,...,26.9%,NaN,NaN,278.0,20.9%,NaN,0.50,0.12,0.27,0
46,fengyue,Top Esports,Support,13.0,69%,38%,8.0,31.0,151.0,5.1,...,6.9%,NaN,NaN,139.0,10.5%,NaN,2.09,0.59,0.40,0
55,JackeyLove,Top Esports,ADC,13.0,69%,62%,63.0,32.0,71.0,4.2,...,27.6%,NaN,NaN,359.0,27.2%,NaN,0.39,0.16,0.37,0
64,Knight,Bilibili Gaming,Middle,22.0,73%,55%,148.0,36.0,155.0,8.4,...,27.8%,NaN,NaN,323.0,23.6%,NaN,0.34,0.13,0.22,0
70,ON,Bilibili Gaming,Support,22.0,73%,50%,16.0,90.0,299.0,3.5,...,8.9%,NaN,NaN,147.0,10.7%,NaN,2.19,0.69,0.58,0
79,Tian,Top Esports,Jungle,13.0,69%,69%,49.0,38.0,90.0,3.7,...,16.0%,NaN,NaN,280.0,21.2%,NaN,0.38,0.29,0.41,0
81,Viper,Bilibili Gaming,ADC,22.0,73%,64%,104.0,55.0,188.0,5.3,...,26.5%,NaN,NaN,355.0,25.9%,NaN,0.60,0.24,0.38,0
86,Xun,Bilibili Gaming,Jungle,22.0,73%,50%,73.0,61.0,239.0,5.1,...,15.2%,NaN,NaN,262.0,19.2%,NaN,0.39,0.26,0.30,0
91,ZUIAN,Top Esports,Top,13.0,69%,31%,39.0,33.0,82.0,3.7,...,22.6%,NaN,NaN,267.0,20.1%,NaN,0.44,0.13,0.15,0
95,Bluffing,Hanwha Life Esports,Support,3.0,67%,33%,4.0,12.0,41.0,3.8,...,9.7%,9.2%,1141.0,160.0,11.5%,0.0,1.92,0.36,0.42,1
105,Delight,Hanwha Life Esports,Support,40.0,75%,50%,47.0,109.0,491.0,4.9,...,7.4%,5.4%,1115.0,157.0,11.2%,0.0,1.91,0.37,0.55,14
109,Doran,T1,Top,40.0,75%,38%,123.0,130.0,234.0,2.7,...,22.9%,22.0%,7102.0,264.0,19.6%,0.0,0.42,0.16,0.18,2
114,Faker,T1,Middle,40.0,75%,53%,156.0,120.0,247.0,3.4,...,23.1%,22.6%,8816.0,289.0,21.3%,0.0,0.46,0.14,0.25,8
117,Gumayusi,Hanwha Life Esports,ADC,43.0,74%,58%,196.0,122.0,337.0,4.4,...,26.8%,28.0%,10837.0,379.0,26.9%,0.0,0.52,0.20,0.36,12
119,Kanavi,Hanwha Life Esports,Jungle,43.0,74%,42%,166.0,157.0,381.0,3.5,...,18.5%,19.7%,3298.0,287.0,20.4%,4.0,0.35,0.30,0.42,15
121,Keria,T1,Support,40.0,75%,50%,47.0,104.0,467.0,4.9,...,9.7%,7.6%,1464.0,148.0,10.8%,0.0,2.18,0.49,0.40,15
130,Oner,T1,Jungle,40.0,75%,58%,152.0,117.0,331.0,4.1,...,16.4%,17.5%,2559.0,275.0,20.3%,5.0,0.37,0.27,0.43,13
133,Peyz,T1,ADC,40.0,75%,55%,212.0,91.0,256.0,5.1,...,28.0%,30.2%,8720.0,382.0,28.0%,1.0,0.42,0.13,0.36,15
154,Zeka,Hanwha Life Esports,Middle,43.0,74%,53%,226.0,86.0,299.0,6.1,...,24.9%,26.1%,7577.0,308.0,21.8%,0.0,0.41,0.18,0.23,7
155,Zeus,Hanwha Life Esports,Top,43.0,74%,49%,142.0,112.0,285.0,3.8,...,22.2%,20.7%,9623.0,275.0,19.6%,0.0,0.46,0.16,0.15,8
161,Bin,Bilibili Gaming,Top,32.0,75%,28%,87.0,87.0,202.0,3.3,...,19.8%,NaN,NaN,274.0,19.6%,NaN,0.45,0.12,0.19,0
167,Creme,Top Esports,Middle,30.0,60%,53%,102.0,70.0,192.0,4.2,...,26.4%,NaN,NaN,284.0,21.6%,NaN,0.41,0.11,0.24,0
173,fengyue,Top Esports,Support,30.0,60%,43%,25.0,102.0,332.0,3.5,...,8.0%,NaN,NaN,143.0,11.0%,NaN,1.96,0.55,0.41,0
186,JackeyLove,Top Esports,ADC,30.0,60%,63%,146.0,84.0,168.0,3.7,...,28.2%,NaN,NaN,351.0,26.6%,NaN,0.37,0.14,0.42,0
196,Knight,Bilibili Gaming,Middle,32.0,75%,50%,224.0,52.0,228.0,8.7,...,25.7%,NaN,NaN,328.0,23.5%,NaN,0.33,0.12,0.28,0
203,ON,Bilibili Gaming,Support,32.0,75%,53%,19.0,98.0,432.0,4.6,...,7.5%,NaN,NaN,148.0,10.6%,NaN,2.19,0.69,0.48,0
218,Tian,Top Esports,Jungle,30.0,60%,37%,108.0,92.0,230.0,3.7,...,16.5%,NaN,NaN,277.0,21.1%,NaN,0.42,0.34,0.40,0
221,Viper,Bilibili Gaming,ADC,32.0,75%,41%,165.0,79.0,254.0,5.3,...,30.3%,NaN,NaN,369.0,26.2%,NaN,0.62,0.26,0.34,0
227,Xun,Bilibili Gaming,Jungle,32.0,75%,59%,142.0,94.0,308.0,4.8,...,16.7%,NaN,NaN,280.0,20.1%,NaN,0.32,0.26,0.31,0
232,ZUIAN,Top Esports,Top,30.0,60%,60%,75.0,93.0,164.0,2.6,...,20.9%,NaN,NaN,256.0,19.7%,NaN,0.47,0.15,0.17,0

### Tại Vòng Khởi Động MSI: Tuyển thủ chuyên nghiệp nào sẽ có KDA cao nhất?

In [18]:
# kiểu éo gì T1 cũng thắng Vòng Khởi Động =))))))
msi_player[msi_player['Team'] == 'T1'].sort_values(by='KDA', ascending=False)

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,DMG%,D%P15,TDPG,EGPM,GOLD%,STL,WPM,CWPM,WCPM,First Blood
133,Peyz,T1,ADC,40.0,75%,55%,212.0,91.0,256.0,5.1,...,28.0%,30.2%,8720.0,382.0,28.0%,1.0,0.42,0.13,0.36,15
121,Keria,T1,Support,40.0,75%,50%,47.0,104.0,467.0,4.9,...,9.7%,7.6%,1464.0,148.0,10.8%,0.0,2.18,0.49,0.40,15
9,Peyz,T1,ADC,9.0,44%,67%,39.0,22.0,60.0,4.5,...,31.6%,34.2%,6966.0,379.0,29.3%,0.0,0.39,0.09,0.39,3
130,Oner,T1,Jungle,40.0,75%,58%,152.0,117.0,331.0,4.1,...,16.4%,17.5%,2559.0,275.0,20.3%,5.0,0.37,0.27,0.43,13
114,Faker,T1,Middle,40.0,75%,53%,156.0,120.0,247.0,3.4,...,23.1%,22.6%,8816.0,289.0,21.3%,0.0,0.46,0.14,0.25,8
17,Oner,T1,Jungle,9.0,44%,44%,36.0,30.0,61.0,3.2,...,18.6%,19.9%,1609.0,271.0,21.1%,1.0,0.32,0.25,0.43,3
18,Keria,T1,Support,9.0,44%,33%,5.0,36.0,94.0,2.8,...,7.0%,5.8%,1226.0,126.0,9.8%,0.0,2.43,1.02,0.39,3
109,Doran,T1,Top,40.0,75%,38%,123.0,130.0,234.0,2.7,...,22.9%,22.0%,7102.0,264.0,19.6%,0.0,0.42,0.16,0.18,2
20,Doran,T1,Top,9.0,44%,44%,20.0,31.0,60.0,2.6,...,22.2%,20.3%,5601.0,256.0,19.9%,0.0,0.39,0.14,0.19,0
22,Faker,T1,Middle,9.0,44%,67%,27.0,36.0,60.0,2.4,...,20.6%,19.9%,7509.0,257.0,20.0%,0.0,0.41,0.14,0.24,1

### Tuyển thủ nào sẽ có chỉ số lính cao nhất trong một trận đấu?

In [19]:
msi_player.sort_values(by='CSPM', ascending=False)[['Player', 'Team', 'CSPM']]

         Player                 Team  CSPM
9          Peyz                   T1  10.9
133        Peyz                   T1  10.3
8      Gumayusi  Hanwha Life Esports  10.2
55   JackeyLove          Top Esports  10.1
117    Gumayusi  Hanwha Life Esports  10.0
186  JackeyLove          Top Esports   9.8
221       Viper      Bilibili Gaming   9.7
1          Zeka  Hanwha Life Esports   9.5
81        Viper      Bilibili Gaming   9.5
154        Zeka  Hanwha Life Esports   9.2
64       Knight      Bilibili Gaming   9.1
167       Creme          Top Esports   9.0
196      Knight      Bilibili Gaming   9.0
161         Bin      Bilibili Gaming   8.9
114       Faker                   T1   8.8
35          Bin      Bilibili Gaming   8.7
20        Doran                   T1   8.7
40        Creme          Top Esports   8.5
22        Faker                   T1   8.5
109       Doran                   T1   8.5
19         Zeus  Hanwha Life Esports   8.4
91        ZUIAN          Top Esports   8.3
155        Zeus  Hanwha Life Esports   8.2
232       ZUIAN          Top Esports   8.2
79         Tian          Top Esports   7.5
218        Tian          Top Esports   7.3
119      Kanavi  Hanwha Life Esports   7.2
227         Xun      Bilibili Gaming   7.1
10       Kanavi  Hanwha Life Esports   7.1
17         Oner                   T1   7.0
130        Oner                   T1   7.0
86          Xun      Bilibili Gaming   6.8
2       Delight  Hanwha Life Esports   1.3
105     Delight  Hanwha Life Esports   1.2
203          ON      Bilibili Gaming   1.1
46      fengyue          Top Esports   1.1
18        Keria                   T1   1.1
70           ON      Bilibili Gaming   1.1
121       Keria                   T1   1.1
173     fengyue          Top Esports   1.0
95     Bluffing  Hanwha Life Esports   1.0

### Tuyển thủ chuyên nghiệp nào sẽ đạt được nhiều Chiến Công Đầu nhất?

In [20]:
msi_player.groupby('Player')['First Blood'].sum().sort_values(ascending=False)
# Dữ liệu về Chiến Công Đầu của các tuyển thủ LPL bị thiếu, nên không thể tính được tổng số Chiến Công Đầu của các tuyển thủ LPL.

Player
Kanavi        18
Keria         18
Peyz          18
Oner          16
Delight       15
Gumayusi      13
Zeus          10
Faker          9
Zeka           7
Doran          2
Bluffing       1
Bin            0
Viper          0
ZUIAN          0
Xun            0
Knight         0
Tian           0
ON             0
JackeyLove     0
Creme          0
fengyue        0
Name: First Blood, dtype: int64

T1 có tham gia Vòng Khởi Động -> chọn Peyz/Keria.

### Tuyển thủ chuyên nghiệp nào sẽ hoàn thành trận đấu với lượng sát thương trung bình cao nhất mỗi trận?

In [21]:
msi_player.sort_values(by='DPM', ascending=False)[['Player', 'Team', 'DPM']]

         Player                 Team    DPM
221       Viper      Bilibili Gaming  919.0
8      Gumayusi  Hanwha Life Esports  887.0
9          Peyz                   T1  866.0
64       Knight      Bilibili Gaming  865.0
133        Peyz                   T1  823.0
81        Viper      Bilibili Gaming  811.0
117    Gumayusi  Hanwha Life Esports  806.0
196      Knight      Bilibili Gaming  800.0
186  JackeyLove          Top Esports  797.0
55   JackeyLove          Top Esports  776.0
1          Zeka  Hanwha Life Esports  760.0
167       Creme          Top Esports  753.0
40        Creme          Top Esports  745.0
154        Zeka  Hanwha Life Esports  743.0
19         Zeus  Hanwha Life Esports  692.0
114       Faker                   T1  686.0
109       Doran                   T1  673.0
155        Zeus  Hanwha Life Esports  664.0
35          Bin      Bilibili Gaming  657.0
91        ZUIAN          Top Esports  640.0
161         Bin      Bilibili Gaming  609.0
20        Doran                   T1  602.0
232       ZUIAN          Top Esports  592.0
22        Faker                   T1  566.0
10       Kanavi  Hanwha Life Esports  564.0
119      Kanavi  Hanwha Life Esports  553.0
227         Xun      Bilibili Gaming  515.0
17         Oner                   T1  512.0
130        Oner                   T1  491.0
86          Xun      Bilibili Gaming  482.0
218        Tian          Top Esports  470.0
79         Tian          Top Esports  446.0
95     Bluffing  Hanwha Life Esports  303.0
121       Keria                   T1  289.0
70           ON      Bilibili Gaming  277.0
2       Delight  Hanwha Life Esports  235.0
203          ON      Bilibili Gaming  228.0
105     Delight  Hanwha Life Esports  223.0
173     fengyue          Top Esports  221.0
18        Keria                   T1  194.0
46      fengyue          Top Esports  190.0